rust_binary(
    name = "hello_world",
    srcs = ["hello_world.rs"],
    rustc_flags = [
        # TODO: Fix these
        "-Cdefault-linker-libraries=y",
        "-Clink-args=-ldl",
        "-Clink-args=-lpthread",
    ],
)

configured_alias(
    name = "hello_world_with_bootstrapped_compiler",
    actual = ":hello_world",
    platform = "bootstrap//platform:stage2",
)
