rust_binary(
    name = "hello_world",
    srcs = ["hello_world.rs"],
    rustc_flags = [
        # TODO(themarwhal): Fix this, unsure why this is needed
        "-Cdefault-linker-libraries=y",
        # TODO(themarwhal): Not sure why this isn't added here:
        # https://github.com/rust-lang/rust/blob/master/library/std/src/sys/unix/mod.rs#L401
        "-Clink-args=-lpthread",
    ],
)

configured_alias(
    name = "hello_world_with_bootstrapped_compiler",
    actual = ":hello_world",
    platform = "bootstrap//platform:stage2",
)
